### ISSUE TITLE
Add-on causes error when opening the "Add" view (Anki 23.10.1)

### ISSUE THREAD

**Issue by ryanzyi** [DarkTrick/AnkiTagSelector#5]
When opening the "Add" view (from the home view by clicking the "Add" button in the top center), Anki catches an exception.

Here's the error message:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-14 00:00:00
Add-ons possibly involved: ⁨TagSelectorV2⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.toolbar", line 411, in _linkHandler
  File "aqt.toolbar", line 426, in _addLinkHandler
  File "aqt.main", line 1230, in onAddCard
  File "aqt", line 136, in open
  File "aqt.addcards", line 50, in __init__
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 601, in main_TSInjection
    tagSelector.createStaticGui(addCardsOrBrowserDialog)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 346, in createStaticGui
    GuiDialogInjector.injectDockingWidget( \
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 464, in injectDockingWidget
    addCardsDialogForm.verticalLayout.insertWidget(posToInsert,mainWindow)
AttributeError: 'Ui_Dialog' object has no attribute 'verticalLayout'

**Comment by DarkTrick** [comment]
Fixed with [version 24.6.3.1](https://github.com/DarkTrick/AnkiTagSelector/releases/tag/v24.6.3.1).
